image: docker:latest

services:
  - docker:dind

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

build:
  tags:
    - dind
  only:
    - tags
  script:
    - IMAGE=$CI_REGISTRY_IMAGE:`echo $CI_COMMIT_TAG | sed 's/^v//'`
    - docker build --pull -t $IMAGE .
    - docker push $IMAGE
